### ISSUE TITLE
metadata information?

### ISSUE THREAD

**Issue by pavlo888** [davised/get_assemblies#2]
Hi @davised 

I am interested in using this package for getting assemblies. However, I was wondering if there is a way to also obtain the metadata for each assembly? By metadata I mean the assembly statistics and some of the information contained in the general report (BioSample, BioProject, Submitter...). 

Cheers, 
Pablo

**Comment by davised** [comment]
Hi Pablo,

Some of that data will be in the metadata.tab file. If you want additional data let me know and I'll add columns for those fields. 

I should document which fields are currently downloaded. I'll add that to the list of things to do. 

If you do a small download you can see what is currently included. 

Cheers, 

Ed

**Comment by pavlo888** [comment]
Hi @davised 

I think the data in the metadata file is just perfect! 

Thanks!

Cheers, 
Pablo
